export const USER_AUTH = 'USER_AUTH';
export const USER_SET_AUTH = 'USER_SET_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR'
export const USER_AUTH_CLEAR_ERROR = 'USER_AUTH_CLEAR_ERROR'